const combatQuotes = [
  // --- Dark Fantasy & Dungeon Core ---
  "The ancient stone gargoyle stirs from its slumber as your blade finds the narrow gap in its granite throat.",
  "Deep within the catacombs, the stench of stagnant water and old decay heralds the arrival of a nameless horror.",
  "Your torch sputters and dies, leaving you to fight the chattering skeletons by the sound of their rattling ribs alone.",

  // --- Romance & Melodrama ---
  "Even in this pit of despair, my heart beats only for the memory of your smile beneath the weeping willow tree.",
  "Is this strike a gesture of hatred, or a desperate plea for the intimacy we lost in the fires of the Great War?",
  "Our love was a fortress built on sand, and now the tide of battle comes to wash the last remnants of us away.",

  // --- Comedy & Meta-Humor ---
  "I would have dodged that fireball, but I was busy wondering if I left the tavern stove on back in the village.",
  "Statistically speaking, you are currently the third most likely person in this room to be eaten by a sentient chest.",
  "The goblin pauses his relentless assault to ask if you have any gluten-free healing potions or perhaps a light snack.",

  // --- News & Media ---
  "Breaking News: Local adventurer enters forbidden tomb despite clearly marked 'Do Not Enter' signs; witnesses are appalled.",
  "In tonight's weather report, we expect a hundred percent chance of blood rain with localized gusts of magical debris.",
  "Experts agree that swinging a massive iron flail is the leading cause of accidental decapitation among the lower classes.",

  // --- Sci-Fi & Cyberpunk ---
  "System Alert: Neon-drenched ghosts are infiltrating the mainframe, and your biological hardware is officially out of warranty.",
  "The chrome glints under the flickering streetlights as the cyborg assassin calculates the trajectory of your inevitable demise.",

  "Strike first. Strike hard. No mercy.",
  "The dragon's breath smelled of sulfur and old coins, a searing heat that melted bronze.",
  "Center your gravity; the power of the punch comes from the earth, not the shoulder.",
  "A flurry of blows landed on the wooden dummy, a rhythmic clatter of pine and precision.",
  "The hydra grew two heads for every one we severed. We need fire, and we need it now!",
  "In the quiet of the dojo, the only sound was the snap of a crisp white gi catching air.",
  "Parry. Riposte. Disengage. The fencer moved like a needle stitching a shroud of steel.",
  "The werewolf's howl shattered the midnight silence, a sound of hunger and silver-hate.",
  "Keep your chin down and your hands up; the moment you drop your guard, the lights go out.",
  "The katana is an extension of the soul, a razor-thin bridge between life and the void.",
  "Beware the siren's song; it pulls the sword from your hand and the breath from your lungs.",
  "Crane style requires balance. Leopard style requires speed. Drunken style requires... a miracle.",
  "The phalanx held. Shield to shield, spear to spear, an unbreakable wall of bronze and grit.",
  "A black belt is just a white belt who never gave up on the path of the warrior.",
  "The manticore's tail lashed out, a poisonous stinger seeking a gap in my heavy plate armor.",
  "Float like a butterfly, sting like a bee. The hands can't hit what the eyes can't see.",
  "The kensei stood motionless in the rain, waiting for the fly to land on his blade's edge.",
  "Sweep the leg! You have a problem with that? Take it up with the referee later.",
  "The gorgon's gaze turned the vanguard into a collection of terrified garden statues.",
  "Muay Thai is the art of eight limbs: two fists, two feet, two knees, and two elbows.",
  "The arrow hissed through the canopy, finding the narrow slit in the orc's rusted helmet.",
  "A tactical retreat is just a fancy way of saying we are running for our lives. Move!",
  "The shadow monk vanished in a puff of smoke, reappearing behind the guard with a cold grin.",
  "Enter the dragon, exit the victim.",
  "The claymore was five feet of Scottish fury, vibrating with the impact of every heavy swing.",
  "Breathe in the chi. Let it flow from the dantian to the fingertips like liquid lightning.",
  "The kraken's tentacle crushed the hull like an eggshell, dragging the screaming crew into the abyss.",
  "A true master wins the fight before the first blow is even exchanged. Avoidance is victory.",
  "The gladiator's sand was stained crimson, a grim reminder of the price of the crowd's roar.",
  "Karate begins and ends with courtesy. Respect your opponent, even as you dismantle them.",
  "The chimera breathed a three-fold terror: goat's fire, lion's teeth, and serpent's venom.",
  "Stay light on the balls of your feet; a stationary target is just a future corpse.",
  "The switchblade clicked open in the dark alley—a metallic snarl of urban predation.",
  "Wing Chun focuses on the centerline. Direct. Efficient. Brutal.",
  "The phoenix burst into flames upon its death, only to be reborn from the smoking cinders.",
  "Double tap. One to the chest, one to the head. Standard operating procedure.",
  "The viking's bearded axe bit deep into the oak shield, splinters flying like lethal confetti.",
  "Jeet Kune Do is the art of expressing the human body. Be like water, my friend.",
  "The minotaur roared in the heart of the labyrinth, the sound echoing off the bloody walls.",
  "A shield is not just for defense; it is a blunt force instrument for crushing ribs.",
  "The ninja's tabi boots made no sound on the tiled roof, a whisper of silk against stone.",
  "Never bring a knife to a gunfight, unless you are very, very fast.",
  "The centaur's hooves drummed a thunderous rhythm across the grassy plains of the north.",
  "Iaido is the art of the draw. The fight is over before the sword is fully out of the scabbard.",
  "The vampire moved with a predatory grace that defied the very laws of human physics.",
  "Pressure points: the body's secret map of pain and paralysis. One touch is all it takes.",
  "The golem was a mindless engine of clay and claymore, unstoppable and utterly without pity.",
  "A skirmish is a test of nerves. A war is a test of logistics and stubbornness.",
  "The drunken master swayed like a willow in the wind, dodging every punch by a hair's breadth.",
  "An eye for an eye makes the whole world blind, but a kick to the shin makes them limp.",
  "The valkyrie descended from the storm, her spear glowing with the light of the aurora.",
  "Keep your ego outside the ring. The canvas is a very honest place to find your limits.",
  "The lich's staff pulsed with necrotic energy, chilling the very marrow in my bones.",
  "Feint high, strike low. The eyes are easily deceived by a flashy hand and a silent foot.",
  "The samurai's seppuku was a final act of honor in a world that had forgotten the word.",
  "Crouching tiger, hidden dragon.",
  "The mace is a simple tool for a complicated problem: plate armor. Just smash it.",
  "A counter-attack is the most dangerous weapon in the arsenal of a patient fighter.",
  "The harpy's shriek cracked the glass in our lanterns, leaving us blind in the aerie.",
  "Jiu-jitsu is the gentle art of folding clothes while people are still inside them.",
  "The berserker felt no pain, only the red haze of the rage and the weight of the hammer.",
  "Shadowboxing is a fight against your greatest enemy: yourself. Don't lose.",
  "The griffon dived from the sun, its golden feathers shimmering like a thousand daggers.",
  "A rapier is a duelist's toy, but in the right hands, it's a lethal sliver of quicksilver.",
  "The monk's vow of silence didn't stop his fists from making a whole lot of noise.",
  "Armor is just a metal coffin if you don't know how to move in it.",
  "The basilisk's trail was a path of stone statues, each one a frozen moment of pure terror.",
  "Seven stars, eight steps. The kung fu forms are a dance of ancient, lethal geometry.",
  "The cavalry charge hit like a tidal wave of horseflesh, steel, and screaming men.",
  "An empty hand can still hold the power of a mountain if the spirit is focused.",
  "The necromancer didn't fight his own battles; he just invited his old friends back.",
  "A jab is a probe. A cross is a statement. A hook is a period at the end of the sentence.",
  "The troll's skin was like pebbled granite, immune to anything but the hottest fire.",
  "Focus your kiai! Let the shout come from your soul and shatter your opponent's resolve.",
  "The spiked morning star swung in a deadly arc, a constellation of pain and iron.",
  "In the clinch, there are no secrets. Just sweat, breath, and the struggle for leverage.",
  "The dragon-slayer's blade was forged in dragon-fire, a poetic irony not lost on the beast.",
  "The bowstring hummed—a single, low note that signaled the end of the conversation.",
  "Size matters not. Look at me. Judge me by my size, do you?",
  "The gargoyle uncurled from the cathedral spire, its stone wings scraping like a tombstone.",
  "The world is a dojo. Every interaction is a lesson. Every setback is a sparring match.",
  "The gladiator's net was a spider's web, designed to tangle the reckless and the brave.",
  "Bushido: the way of the warrior is found in death. Live as if you are already gone.",
  "The nunchaku whirled in a blur of yellow wood, a defensive perimeter no one dared cross.",
  "A knight in shining armor has never had his metal truly tested. Look for the dents.",
  "Victory is reserved for those who are willing to pay its price in blood and discipline."
]