// --- Cooking Quotes ---
const cookingQuotes = [
  "The fire needed tending the way a garden does - a little attention, a little patience, and a willingness to sit quietly and let things take their time. He added a log and watched the sparks rise into the dark, each one a brief, bright life against the black sky.",
  "She learned to cook from a woman who never used measurements. A handful of this, a pinch of that, cook it until it smells right. It was an infuriating system until the day she understood that it wasn't a system at all, but a conversation between the cook and the ingredients.",
  "The campfire reduced all social hierarchy to nothing. It didn't matter who you were or what you owned; if you could keep a fire burning and make something edible over it, you had the only skill the situation required. The man who had cooked a fish over a driftwood fire was richer than any king in a palace.",
  "There is a particular satisfaction in cooking something from scratch in the open air. No appliance, no gadget, no recipe on a glowing screen. Just heat, and raw ingredients, and your own hands moving through the work of turning one thing into another, better thing.",
  "He watched the water come to a boil in the small pot and thought about how strange it was that this moment - this ordinary, ancient moment of water and heat - had happened a billion times in human history, in every language, on every continent, and it was happening again right now.",
  "The fish had been in the water an hour ago. She thought about that as she laid it over the fire. How quickly a thing could move between worlds. The gap between the living and the cooked was just a matter of heat and a few minutes, and it struck her as both deeply ordinary and quietly profound.",
  "Cooking over an open fire requires a kind of attention that a modern kitchen does not. You cannot set a timer and walk away. The fire does not have settings. You have to stay close, watch the color of the heat, listen to the sound of the fat in the pan, and adjust. It demands your presence.",
  "The smell of woodsmoke and cooking fish drifted through the camp and woke people who had not planned to wake. It was the most ancient alarm clock, built into the human body somewhere below language, the smell of food and safety that had been waking us up since before we had words for either.",
  "She had packed light for the trip, but she had packed correctly. Good flint, dry tinder, enough food. The test of a good camper, her father said, was not whether they had everything they wanted, but whether they had everything they needed, and whether they knew the difference.",
  "The iron pan had belonged to three generations of the same family, and it showed. It was seasoned black and smooth, the accumulated residue of a thousand meals pressed into its surface like a kind of culinary memory. Whatever he cooked in it tonight would become part of that history.",
  "He ate slowly, the way you eat when you have earned a meal. Not because you are being mindful, not because someone told you to savor it, but because your body had been working hard all day and the food was actually, genuinely good, and there was no reason in the world to hurry.",
  "The fire was too hot to get close to, which meant it was exactly right for cooking. She had learned this early: a fire you can sit near comfortably is a fire too cool for anything except looking at. A proper cooking fire pushes you back a little. It insists on being taken seriously.",
  "There is no lonelier or more satisfying sound than the hiss of raw fish hitting a hot pan in the middle of nowhere. It announces that something is happening, that the day's work is converting itself into the evening's reward, that the gap between hunger and eating is finally beginning to close.",
  "He had burned the first fish and eaten it anyway, because he was hungry and because wasting food out here felt like a serious moral failure. The second fish he cooked more carefully, watching the edges for the pale color that moved inward like a tide, pulling it off the heat at exactly the right moment.",
  "The wind shifted and blew smoke directly into her face for the third time. She moved around the fire and it shifted again. She moved again. The fire followed her with patient malice until she gave up and stood in the smoke and stopped caring, which was probably the lesson the fire was trying to teach her.",
  "Cooking together, they discovered, was a kind of shorthand for a relationship. You could learn more about a person from an hour of sharing a campfire and a meal than from a week of ordinary conversation. The way someone tended a fire said something real about who they were.",
  "The recipe, if you could call it that, was simplicity in its purest form. Fish. Fire. Salt if you have it. Time. Nothing to hide behind, nowhere for mediocre ingredients to go. The campfire was the most honest kitchen he had ever worked in.",
  "She kept the fire small and controlled, the way her grandfather had taught her. A big fire looks impressive but gives you less. A small, hot fire does the work. The same was true, she thought, of most things that actually mattered in life.",
  "The coals were better than the flame. Once the fire had burned down to a red, pulsing bed of charcoal, the real cooking could begin. Flame was for spectacle. Coals were for patience and for the deep, slow heat that turned raw things into something worth eating.",
  "They sat around the fire after eating, not talking much, watching it burn down. There was nothing that needed saying. The meal had been simple and had been enough. The fire was warm. The dark outside the circle of light was soft and full of small sounds. This, he thought, was as good as things got.",
  "Mise en place is the religion of the organized chef.",
  "Warning: The bottom of the pan is extremely hot. Do not touch with bare hands.",
  "A pinch of saffron costs more than gold but tastes like a sunset caught in a cloud of rice.",
  "Tonight on Action News: Is your air fryer a fire hazard? We investigate at eleven.",
  "Fold the egg whites gently; if you pop the bubbles, the souffle will fall like a lead balloon.",
  "The street taco was a masterpiece of charred al pastor, pineapple, and a zesty salsa verde.",
  "Deglaze the pan with a splash of dry white wine to scrape up those delicious brown bits.",
  "Grandma never used a measuring cup. She just knew when the dough felt like a baby's earlobe.",
  "Sous-vide cooking is the art of patience, water, and plastic, resulting in a perfect medium-rare.",
  "Salt, fat, acid, heat. Balance these four, and you can rule any kitchen in the world.",
  "The garlic hit the hot oil and the kitchen immediately smelled like heaven's own cafeteria.",
  "Sushi is a silent conversation between the blade, the fish, and the seasoned vinegared rice.",
  "Is it supposed to be smoking like that? No, honey, call the pizza place. Now.",
  "A true roux takes time; you have to stir it until it's the color of an old penny.",
  "The Umami bomb exploded on my tongue-truffles, parmesan, and slow-roasted tomatoes.",
  "Blanch the broccoli in boiling water for sixty seconds, then shock it in an ice bath.",
  "Molecular gastronomy turns dinner into a science experiment with edible foams and spheres.",
  "The cast iron skillet is a heavy, black heirloom that seasoned a century of Sunday breakfasts.",
  "Kimchi is a spicy, funky fermented hug from Korea that wakes up every single taste bud.",
  "Knife skills are the difference between a salad and a pile of roughly chopped debris.",
  "Julienne the carrots into matchsticks, then dice the onions until you start to cry.",
  "The brisket sat in the smoker for fourteen hours, emerging with a dark, peppery bark.",
  "Ratatouille is just a peasant stew, but when plated in a spiral, it becomes a work of art.",
  "Can you pass me the microplane? This lemon needs zesting before the cake goes in.",
  "The smell of roasting coffee beans is the only reason I agree to wake up in the morning.",
  "Braising is the magic trick that turns a cheap, tough cut of meat into butter.",
  "Authentic Neapolitan pizza must be charred by wood fire and topped with buffalo mozzarella.",
  "Too much salt? Add a peeled potato to the pot; it'll soak up the excess like a sponge.",
  "The pastry chef's hands were covered in flour, a ghost haunting the marble countertop.",
  "Gumbo is a slow dance of okra, file powder, and the holy trinity of celery, onions, and peppers.",
  "The blender roared, turning frozen mangoes and coconut milk into a tropical slushy.",
  "A dull knife is more dangerous than a sharp one. Respect the edge.",
  "The Great British Bake Off has ruined my standards for sponge cakes; no soggy bottoms!",
  "Searing a steak creates the Maillard reaction, a chemical miracle of flavor and crust.",
  "Honey never spoils. Archaeologists found edible honey in ancient Egyptian tombs.",
  "The crepe was paper-thin, folded over Nutella and dusted with a snowstorm of powdered sugar.",
  "Always rest your meat for ten minutes after cooking, or the juices will run away forever.",
  "The mortar and pestle ground the peppercorns into a fragrant, gritty dust.",
  "Is that cilantro or parsley? One makes it a taco; the other makes it a garnish.",
  "Tempering chocolate is a nightmare of temperatures and crystal structures.",
  "The pressure cooker hissed like a steam engine, threatening to launch its lid into orbit.",
  "Tofu is a sponge for flavor; it's only boring if the chef is boring.",
  "The poutine was a messy pile of fries, squeaky cheese curds, and thick brown gravy.",
  "Baking is a science. Cooking is an art. Don't mix up the two or your bread won't rise.",
  "The copper pots hung from the ceiling, gleaming like burnished shields in a culinary armory.",
  "Reduce the balsamic vinegar until it's a thick, syrupy glaze that coats the back of a spoon.",
  "Escargot: because everything tastes better when drenched in garlic butter and parsley.",
  "The wok breathed fire, a technique called 'wok hei' that imparts a smoky charred essence.",
  "Breakfast is served! Dig into these fluffy pancakes before the maple syrup gets cold.",
  "The buffet was an endless sea of shrimp cocktail and carved prime rib.",
  "Chiffonade the basil by stacking the leaves, rolling them tight, and slicing thin ribbons.",
  "A dash of nutmeg in a white sauce is the secret ingredient no one can ever quite name.",
  "The dumpling skins were translucent, revealing the pink shrimp and green chives inside.",
  "Fire up the grill! We've got corn on the cob, bratwurst, and enough coal to power a train.",
  "The tajine trapped the steam, swirling the scents of lamb, apricots, and cinnamon.",
  "I burned the toast again. It's not 'charred,' it's 'artisanal carbonized wheat.'",
  "The infusion of hibiscus turned the tea a brilliant, shocking shade of crimson.",
  "Don't overwork the biscuit dough, or you'll end up with hockey pucks instead of fluff.",
  "The Michelin star is a heavy burden to carry for a restaurant made of glass and ego.",
  "Pesto: the green gold of Italy, pounded by hand to keep the basil from bruising.",
  "The deep fryer gurgled, turning pale batter into a golden, crispy armor for the cod.",
  "A mandoline slicer is a thumb's worst enemy. Use the guard or lose a layer.",
  "The venison was served with a tart huckleberry reduction and a side of roasted parsnips.",
  "Leftovers are better on the second day because the flavors finally had time to introduce themselves.",
  "The tandoor oven reached five hundred degrees, slapping the naan against its clay walls.",
  "Zoodles are not pasta. They are lies made of zucchini. Give me the carbs.",
  "The smell of baking cinnamon rolls is the ultimate psychological warfare.",
  "Clarified butter, or ghee, has a high smoke point perfect for sautéing at high heat.",
  "The broth had been simmering for forty-eight hours, a liquid essence of bone and marrow.",
  "Tapas are small plates meant for big conversations and even bigger glasses of wine.",
  "The soufflé didn't rise. I'm going to go cry in the pantry now.",
  "Fermentation is just controlled rotting, and it is absolutely delicious.",
  "The food truck served kimchi fries to a line of hipsters that stretched around the block.",
  "A splash of fish sauce smells like regret but tastes like pure, savory magic.",
  "The crème brûlée gave a satisfying 'crack' when the spoon shattered the sugar crust.",
  "Is the pasta al dente? Throw it at the wall and see if it sticks. (Just kidding, please don't.)",
  "The avocado was perfectly ripe for exactly twelve seconds. I missed it.",
  "To make a great burger, you need a high fat-to-lean ratio. 80/20 is the golden rule.",
  "Bon appétit!"
];