// --- Fishing Quotes ---
const fishingQuotes = [
  "The lake was glass in the early morning, unmarked by wind or worry. Daniel set his line and let the silence do its work. Fishing, he had learned, was not about the fish at all. It was about learning to be still in a world that never stopped asking you to move.",
  "She cast the line with the ease of someone who had done it ten thousand times. The lure arced through the amber light of late afternoon and kissed the water without a ripple. Her grandfather had taught her this, and his grandfather had taught him, a chain of patience stretching back to the edge of memory.",
  "The river ran cold and fast over polished stones, the color of old pewter under the overcast sky. Marcus waded in up to his knees and felt the current push against him with a quiet, indifferent force. He had fished this stretch for thirty years, and it still surprised him every single time.",
  "There is a particular kind of loneliness that is not unpleasant. It finds you at the end of a dock, feet dangling, watching the bobber drift. The town is visible across the water, its sounds reduced to a murmur. You are apart from it, briefly, and the separation feels like a gift you did not know to ask for.",
  "The salmon run was something you had to see to believe. They hurled themselves upstream with a ferocity that seemed to defy the current, the cold, and their own exhaustion. Elena watched from the bank, her rod forgotten in her hand. Some things were too elemental to interrupt with the business of catching.",
  "He had been fishing the same reef for forty years and had never once found the bottom of it. Every drop of the line was a question sent into the dark and answered only sometimes, and never in the way you expected. The ocean kept its secrets well, and he respected it enormously for that.",
  "The trout rose to the fly with a delicacy that seemed impossible for a creature of muscle and instinct. One moment the surface was smooth, the next it was a small, perfect explosion of water and silver. She set the hook and felt the line go taut and alive in her hand, a telegraph wire to another world.",
  "Ice fishing is a form of optimism. You drill through two feet of frozen lake and drop a line into the dark, cold water below and you wait. The wind might be cutting across the open ice at thirty miles an hour. But you wait, because somewhere down there, the fish are waiting too.",
  "The fishing boat left the harbor before the sun came up, its engine a low, reliable grumble in the dark. By the time the light came, they were far enough out that the coast was a thin smear on the horizon. The sea was enormous and they were very small in it, and that was exactly the point.",
  "A fly rod in hand transforms a river into a puzzle. You read the current, the eddies, the shadow of a submerged log, the dimples where the trout are rising. Every cast is a hypothesis. The fish is the experiment. Most of the time, the experiment fails, but the hypothesis is always worth testing.",
  "The old man kept the fish alive in the water beside the boat while he decided. It was a good fish, heavy and well-formed, the kind you wanted to show people. Then he thought about the river and about the fish's long journey to get here, and he opened his hand and let it go.",
  "Night fishing required a different kind of attention. You could not see the water, only hear it. Your hands learned to read the line for what your eyes could not. Every twitch and pause became significant in the darkness, a language of subtle signals from the deep that you had to learn to speak.",
  "She had read every book on fly fishing, memorized the Latin names of the insects, tied her own flies with the precision of a jeweler. Then she stood in the river for the first time and realized that no book had adequately described the current against her legs or the way the light moved on the water.",
  "The shrimp came up in the net in a mass of translucent pink, their legs still working in the open air. It was an uncanny thing, that abundance. The fisherman sorted through them with quick practiced hands, throwing back the small ones, keeping the rest. The sea provided, as it had always provided, if you knew how to ask.",
  "Deep sea fishing is a negotiation with forces that do not recognize your existence. The marlin on the end of the line does not know you are there; it only knows the hook and the pull and the strange resistance that has attached itself to its life. You are an inconvenience to it, nothing more.",
  "The pond behind the farmhouse was so shallow you could see the bass holding in the shade of the dock. Catching them felt almost unfair, but the boy did not think about fairness. He thought about the weight of the fish in his hands and the way its colors faded once you took it from the water.",
  "Fishing with a child requires the suspension of all your own ambitions. You are no longer there to catch fish. You are there to bait hooks and untangle lines and explain why we have to be quiet and then explain it again. But when the bobber goes under and the child shrieks with joy, you remember why you started.",
  "The tidal flats stretched for miles at low water, and you could walk them for hours without seeing another person. She dug for clams in the exposed mud, working methodically, listening to the distant sound of the sea rearranging itself. This was an older kind of fishing, before rods and lines, before equipment.",
  "The kayak moved silently through the mangroves, and he kept his paddle still while he cast into the shadows. Snook were creatures of ambush, and catching them required thinking like one. He had been at this for three hours and had not had a bite, but the mangroves were worth being in regardless of the fish.",
  "Hook, line, and sinker.",
  "The water is glass today.",
  "A bad day of fishing beats a good day at the office.",
  "Patience is the only bait that never runs out, though the fish might.",
  "The bobber dipped, danced, and then vanished into the dark, rippling mirror of the lake.",
  "Early bird gets the worm, but the early fisherman gets the trophy bass hiding in the reeds.",
  "The drag screamed as the line peeled off the reel; whatever was on the other end was massive.",
  "Saltwater runs in my veins, and the rhythmic sound of the surf is the only lullaby I need.",
  "Trout are the aristocrats of the stream, dressed in speckled finery and possessing a weary wisdom.",
  "To catch a predator, you must think like one. Move slow. Stay low. Watch the shadows.",
  "The old man said the biggest fish are the ones that get away, growing larger in every retelling.",
  "Fly fishing is an act of grace—a delicate loop of silk uncurling over a mountain cold-spring.",
  "Beware the Kraken's reach.",
  "I cast my worries into the tide and waited for the ocean to wash the salt into my wounds.",
  "Scale by scale, the salmon fought the current, a silver bullet propelled by ancient, primal instinct.",
  "The bait shop smelled of brine, old wood, and the quiet desperation of men chasing a dream.",
  "Carbon fiber rods bend but rarely break, a feat of modern engineering against the weight of the sea.",
  "Carp are the scavengers of the silt, vacuuming up the secrets of the muddy river bottom.",
  "A lure is just a colorful lie we tell the fish to convince them to join us for dinner.",
  "Moonlight hit the scales of the tarpon, turning the beast into a shimmering ghost of the deep.",
  "Cast. Retrieve. Repeat. The meditation of the shoreline is a cure for a cluttered mind.",
  "The net came up heavy, dripping with sea foam and the squirming silver of a thousand sardines.",
  "Marlin are the gladiators of the blue water, leaping high to shake the steel from their jaws.",
  "Don't count your fish until they're in the cooler.",
  "The ice auger bit deep into the frozen crust, revealing the black, freezing heart of the pond.",
  "Nylon line is invisible to the fish, but to the fisherman, it is the only tether to reality.",
  "Bioluminescence sparked in the wake of the boat, a galaxy of neon plankton glowing in the dark.",
  "A hook is a question asked of the water, and a bite is the ocean's definitive answer.",
  "He wore his grandfather's lucky hat, though the grease stains suggested the luck had dried up years ago.",
  "The pike waited in the weeds like a submerged log, its yellow eyes tracking the passing minnows.",
  "Sturgeon are living fossils, armored giants that have cruised these murky depths since the dinosaurs.",
  "The tide waits for no man, and neither do the mackerel when they're running toward the bay.",
  "A tangled line is a test of character. A snapped line is a test of vocabulary.",
  "The pier creaked under the weight of the salty crowd, all staring intently at the rising tide.",
  "Barracuda teeth are like serrated razors, designed to snap shut on anything that glints in the sun.",
  "The fog was so thick I couldn't see the bow of the boat, let alone the buoy marking the reef.",
  "Is it a bite or just a weed? The eternal question of the novice angler.",
  "The smell of frying catfish is the official scent of a successful summer afternoon.",
  "Deep sea fishing is ten hours of boredom punctuated by ten minutes of absolute, terrifying chaos.",
  "Waders are just portable bathtubs that eventually leak in the exact place you don't want them to.",
  "The river is a highway for the soul.",
  "Catfish possess whiskers called barbels, which are loaded with taste buds to find food in the dark.",
  "We followed the gulls; where the birds dive, the baitfish hide, and the tuna are never far behind.",
  "Keep your fingers away from the gills.",
  "The sun set fire to the horizon, turning the ocean into a sea of liquid gold and copper.",
  "A dry fly must land as soft as a kiss on the surface of the water to fool a clever rainbow trout.",
  "The pressure at the bottom of the Mariana Trench would crush a human, yet life still thrives there.",
  "Eels are slippery customers, winding themselves into knots of slime and frustration.",
  "I don't fish to find myself; I fish to lose the person the world expects me to be.",
  "The outboard motor sputtered and died, leaving us at the mercy of the wind and the incoming storm.",
  "Jellyfish drifted past like translucent umbrellas, beautiful but carrying a stinging, hidden venom.",
  "A fisherman is a man who stands in the rain with hope in his heart and water in his boots.",
  "Snapper are clever. They'll pick the bait off the hook and leave you with nothing but a bare point.",
  "The kelp forest swayed in the surge, a cathedral of green light and hidden, scaly congregants.",
  "Anchors aweigh!",
  "The Great Barrier Reef is a masterpiece of coral, but it's the fish that provide the movement and color.",
  "A heavy sinker ensures your bait reaches the strike zone before the current sweeps it away.",
  "Some people fish for food. Others fish for sport. I fish because the silence is too loud elsewhere.",
  "The shark circled the boat, a grey fin cutting the water with terrifying, effortless precision.",
  "Squid use jet propulsion to dart through the deep, leaving behind a cloud of ink to mask their escape.",
  "Tight lines!",
  "The reel whistled a high, metallic tune as the monster took a hundred yards of line in seconds.",
  "A tackle box is a treasure chest of plastic worms, rusted spoons, and half-remembered stories.",
  "Crabbing involves a lot of waiting for a small, delicious reward that fights back with pincers.",
  "The water was so clear I could see the individual pebbles on the bottom, twenty feet down.",
  "The compass needle spun wildly as we entered the cove, as if the rocks themselves were magnetic.",
  "Mahi-mahi change colors when they're excited, flashing brilliant shades of electric blue and neon yellow.",
  "The dock was slippery with algae, a green trap for the unwary fisherman rushing to his boat.",
  "I cast toward the lily pads, hoping for a largemouth bass but expecting only a snagged hook.",
  "Life is short. Fish hard.",
  "The ocean is a vast graveyard of lost lures and broken dreams, but today it gave me a dinner.",
  "A harpoon is a primitive tool, but in the hands of a master, it is as precise as a surgeon's blade.",
  "Flounder are masters of disguise, flattening themselves against the sand until they are invisible.",
  "The pressure of the deep turns ordinary fish into pale, bioluminescent nightmares with giant teeth.",
  "The first cast of the morning is always the most hopeful.",
  "We used a chum bucket to stir the water into a frenzy, attracting every hungry fin for miles.",
  "The river doesn't care about your problems; it just keeps flowing toward the inevitable sea.",
  "Tuna can swim at speeds of up to forty-five miles per hour, making them the Ferraris of the ocean.",
  "The anchor gripped the rocky ledge, holding us steady against the howling gale and the rising swell.",
  "When the drag stops clicking, you've either won the fight or lost the fish.",
  "There is no such thing as 'enough' fishing gear."
];