// --- Forge / Smithing Quotes ---
const forgeQuotes = [
  "Steel is born in the heat of the furnace.",
  "The anvil answers every blow with equal resolve.",
  "A good blade remembers the hammer that shaped it.",
  "Fire does not ask permission to transform what it touches.",
  "Metal has no opinion. The smith has all of them.",
  "Every ingot was once earth, patient and waiting.",
  "The forge has no mercy for uncertain hands.",
  "Work the metal while it glows or lose it to cold.",
  "A sharp edge requires patience far more than force.",
  "Iron yields only to those who understand it.",
  "In the forge there is no room for hesitation.",
  "The quality of steel reveals the quality of the mind behind it.",
  "One honest blow is worth a thousand nervous taps.",
  "The fire is the teacher and the anvil is the lesson.",
  "Copper and tin, unlikely kin, become something greater together.",
  "Gold does not rust because it has surrendered nothing impure.",
  "The hammer sings a plain song and the metal slowly learns it.",
  "Impurities vanish in heat if the heat is fierce enough.",
  "Every mark on the anvil is a lesson passed forward.",
  "A smith knows the metal by touch long before sight confirms it.",
  "Silver does not ask to be beautiful. It simply is.",
  "To forge is to impose your will on something that resists.",
  "Coal and iron, an alliance older than written history.",
  "Patience at the forge saves recklessness at the battlefield.",
  "The strongest armour begins as the most stubborn ore.",
  "Shape it now or let another shape it for you.",
  "Bronze was the first proof that two weaknesses can become a strength.",
  "The forge respects no rank. Only craft matters here.",
  "A bar of iron is a promise not yet kept.",
  "Heat reveals character in metal as in men.",
];