const miningQuotes = [
  "The rhythmic clink of the pickaxe is the heartbeat of the mountain, pumping ore into the world above.",
  "Deep beneath the crust, the pressure turns simple carbon into a crystalline masterpiece of pure light.",
  "Never trust a ceiling that whispers; if the shale begins to flake, you drop your haul and you run.",
  "A vein of pure silver is a jagged lightning bolt frozen in a wall of cold, unyielding granite.",
  "The canary in the cage is the only thing standing between a hardworking miner and a pocket of silent gas.",
  "Emeralds aren't just stones; they are fragments of a forest that the earth decided to swallow and petrify.",
  "Your lantern light is a fragile bubble of safety in an ocean of crushing, ancient darkness.",
  "To find the motherlode, one must be willing to crawl through the narrowest cracks in the foundation of the world.",
  "The scent of ozone and wet stone fills the shaft as the drill bits bite into a fresh layer of conductive copper.",
  "Mica flakes shimmer like fallen stars against the soot-stained walls of the damp lower tunnels.",
  "Magnetite can pull the very compass from your hand, leaving you lost in a labyrinth of identical gray stone.",
  "Every handful of dirt removed is a small victory against the mountain's stubborn refusal to share its wealth.",
  "Obsidian is the earth's glass, born in the fire of a volcano and cooled into a razor-sharp shadow.",
  "The timber supports groan under the weight of a thousand tons of rock, a constant reminder of our mortality.",
  "Gold has a way of glowing even when there is no light to reflect, as if it remembers the sun from long ago.",
  "Geodes are humble on the outside, looking like common river rocks until the hammer reveals their crystalline heart.",
  "The dust of a thousand crushed garnets covers the floor like a carpet of frozen, dark red sparks.",
  "A master miner knows the difference between the sound of solid bedrock and the hollow ring of a hidden cavern.",
  "Sulfur hangs heavy in the air, a stinging reminder that we are intruders in a realm that belongs to the heat.",
  "Lapis lazuli is the blue of a midnight sky, trapped forever in a tomb of white calcite and golden pyrite.",
  "There is a certain madness that comes from spending too long chasing the glint of a disappearing seam.",
  "Bismuth crystals grow in geometric spirals, like a city built by machines from a dimension made of pure metal.",
  "The elevator rattle is a nervous song, sung by a steel cable that prays it can hold the weight of the day's greed.",
  "Topaz and tourmaline hide in the pockets of pegmatite, waiting for the first ray of light to hit them in an aeon.",
  "The deeper we go, the warmer the stone feels, as if the planet itself is annoyed by our persistent scratching.",
  "Malachite and azurite swirl together like a storm on a distant planet, frozen in a chunk of heavy carbonate.",
  "Anthracite coal is the black diamond of the poor, burning with a steady blue flame that keeps the winter at bay.",
  "A pickaxe is more than a tool; it is an extension of the arm, a tooth of steel that bites the hand of the earth.",
  "Amethyst cathedrals are the most beautiful places a man can die, surrounded by purple spikes and silence.",
  "The geology of this region is a chaotic mess of folded schist and intrusive quartz that defies all logic.",
  "Schist and shale might crumble easy, but they hide the sharpest secrets of the tectonic plates above.",
  "We are the scavengers of the crust, picking the bones of a giant that hasn't moved in a billion years.",
  "Tungsten is the stubborn king of metals, refusing to melt or break while the rest of the tools shatter to pieces.",
  "A single flaw in a diamond can be the difference between a king's crown and a glazier's scrap pile.",
  "The cave water drips with a slow, agonizing tempo, counting the seconds until the shift finally ends.",
  "Fossilized amber holds the sunlight of a prehistoric afternoon, sticky and sweet and hard as a rock.",
  "Don't be fooled by 'Fool's Gold'; pyrite is a harsh mistress that breaks your tools and gives nothing back.",
  "The iron bloom in the furnace is the fruit of a week spent sweating in the lightless belly of the pit.",
  "Raw turquoise looks like the scales of a desert dragon, buried in the parched earth of a forgotten canyon.",
  "When the mountain speaks in a low, rumbling bass, it is time to put down the shovel and find the surface.",
  "The air at the four-thousand-foot level is a soup of diesel exhaust, rock dust, and the metallic tang of oxidation, a thick atmosphere that feels as though the mountain itself is trying to press the breath right out of your lungs. You learn to breathe shallow, to move with purpose, and to never waste a single match on a damp wick when the shadows start to close in from the edges of the vertical shaft.",
"To the uninitiated, a geode is just a lumpy, unattractive gray orb rolling in a dry creek bed, but to the seasoned miner, it is a stone egg waiting to hatch a forest of purple quartz. The moment of the break is sacred; the sharp crack of the hammer reveals a hollow cathedral of shimmering points that haven't reflected a single photon of light since the continents were a single, drifting landmass.",
"Deep-sea mining is a different kind of nightmare; instead of the crushing weight of the rock above, you feel the absolute embrace of a thousand atmospheres of cold, black water pressing against the reinforced hull of your submersible. Out there in the brine, the manganese nodules sit like scattered coins on the abyssal plain, waiting for a mechanical claw to pluck them from the silent silt of a million years.",
"There is a peculiar madness that takes hold of a person who has spent too many months chasing a fading seam of silver through the labyrinthine guts of a dying mountain range. You start to see faces in the jagged limestone and hear the chattering of long-dead prospectors in the rhythmic drip of the groundwater, warning you that some treasures were never meant to see the light of a flickering torch.",
"Bismuth crystals are the master architects of the mineral kingdom, growing in iridescent, stair-stepped hoppers that look like the neon ruins of a miniature cyberpunk city. Their colors shift from peacock blue to sunset pink as the light hits the thin oxide layer, a geometric miracle born from a cooling molten heart that defies the messy randomness of the mud and common dirt surrounding it.",
"The industrial crusher at the surface is a gluttonous beast, its massive steel teeth gnashing together with a thunderous roar that can be heard for miles across the desolate moor. It cares nothing for the delicate beauty of the gems or the scientific history of the fossils; it only craves the raw material, reducing the mountain's pride into a uniform grit ready for the chemical vats and the smelting fires.",
"Every master miner has a lucky charm - perhaps a smooth piece of river jade, a fossilized shark tooth, or a spent blasting cap from their very first successful strike - that they keep tucked away in a pocket. In a world governed by the brutal laws of structural engineering and geological luck, a little bit of superstition is often the only thing that keeps a person sane while working in the absolute dark.",
"The elevator cage is a rickety basket of rusted iron and heavy grease, plummeting down the vertical shaft with a speed that leaves your stomach somewhere near the surface. As the temperature rises and the oxygen grows stale, you look at the grime-streaked faces of the other workers in the dim light, seeing the same grim determination etched into their features as they prepare to do battle with the bedrock once again.",
"Tungsten carbide tipped drills are the only things capable of scarring the face of the 'Black Bastion,' a wall of reinforced magnetite that has broken a dozen companies and a hundred spirits. We spend three days just to advance a single meter, the cooling water turning to steam the moment it touches the friction-heated rock, creating a misty purgatory where time seems to stand completely and utterly still.",
"A 'vug' is a secret pocket of beauty in an otherwise ugly stretch of rock, a natural cavity lined with crystals that grew undisturbed in a bath of mineral-rich hydrothermal fluids. Sliding your hand into a fresh vug is a gamble; you might pull out a cluster of museum-quality fluorite, or you might slice your fingers to the bone on the razor-edged shards of hidden, prehistoric crystalline growth.",
"The seismic scanners are lighting up with a frantic, rhythmic pulse, indicating a pocket of highly pressurized gas trapped behind a thin curtain of obsidian just inches from your drill bit. One more inch of penetration could mean a spectacular payday of rare earth elements, or it could mean the entire sector becomes a vacuum-sealed tomb for anyone unlucky enough to be on the graveyard shift tonight.",
"Rare earth minerals like neodymium and dysprosium are the invisible ghosts that haunt our modern technological world, hidden in the clay and silt of remote pits that look like nothing special to the naked eye. We dig through thousands of tons of mundane earth just to extract a few kilograms of the gray powder that allows the world above to speak across the airwaves and fly through the clouds.",
"Magmatic copper deposits form in the cooling veins of ancient volcanoes, a slow-motion plumbing system that carried liquid wealth from the core to the crust over millions of years. When you find a rich deposit, the vibrant green and blue stains of malachite and azurite lead the way like a map drawn in watercolor, pointing toward the heavy, red metallic heart of the strike buried deep in the earth.",
"There is no silence quite like the silence of a deep-sector mine when the heavy machinery stops, a heavy and absolute quiet that makes your own pulse sound like a rhythmic drum in your ears. It is in these moments of stillness that you realize how far you truly are from the wind, the rain, and the rustle of autumn leaves, buried under a billion tons of indifferent, silent tectonic history.",
"Amber is the earth's natural time capsule, a golden drop of resin that captured a moment of prehistoric life and held it tight while the world changed completely around it. To mine amber is to be a thief of time, stealing away the insects and leaves of a forest that turned to stone long before the first human ever thought to pick up a rock and use it as a tool for survival.",
"The tailings pile is a monument to our collective persistence, a gray mountain of discarded hope that grows taller with every passing season of excavation. For every single gram of gold that eventually makes its way to the vault, a thousand tons of shattered stone are cast aside, creating a new landscape of jagged rubble that will eventually be reclaimed by the moss and the hardy mountain weeds.",
"An anthracite coal mine is a world of monochrome shadows, where the only colors are the white of your eyes and the dim orange glow of the safety lamps cutting through the soot. It is a humble profession compared to the gold-seekers, but there is a quiet dignity in pulling the concentrated heat of a prehistoric sun out of the frozen ground to keep the cities above from freezing during the winter.",
"The geology of a major fault line is a chaotic tapestry of shattered schist and intrusive quartz, a place where the earth has ground its own bones into a fine powder through sheer friction. Navigating these zones requires a surveyor with the instincts of a cat, as the ground can shift a dozen inches in a single night, snapping heavy oak supports like they were mere wooden toothpicks.",
"Salt mines are vast, subterranean cathedrals carved out of the remains of ancient, evaporated oceans, where the walls glitter with a crystalline whiteness that mimics the snowfall of the surface. Walking through these halls is a surreal experience, as the air is so dry it cracks your skin and the floor is a solid, crunching pavement of sodium chloride that has been preserved for eons.",
"When the mountain speaks in a low, rumbling bass, it isn't just a sound; it is a physical vibration that rattles your teeth and warns you of the immense pressure held back by a few inches of timber. A veteran miner doesn't wait for the dust to fall from the ceiling; they know that the mountain never misses a chance to reclaim the space we have stolen from its dark and heavy interior.",
"The pickaxe rhythm is the heartbeat of the mountain, a steady pulse against the silent stone.",
  "Warning: Methane levels exceeding safety thresholds in Sector 4. Immediate evacuation is advised.",
  "Bismuth crystals grow in iridescent, hopper-like patterns, resembling a colorful staircase to nowhere.",
  "Deep in the crust, heat and pressure turn the common into the coveted. Diamonds are just carbon with grit.",
  "The canary stopped singing three minutes ago. Why are you still standing there with your mouth open?",
  "He held the raw emerald to the lantern light; it glowed with the envy of a thousand dead kings.",
  "To mine is to gamble with the earth. You put in your sweat, and she decides if you leave with gold.",
  "Lapis lazuli was once ground into pigment to paint the robes of saints and the depths of the sky.",
  "The tunnel groaned, a low, tectonic protest against our intrusion into the planet's ribcage.",
  "Pyrite is the jester of the mineral kingdom, wearing a golden mask to mock the desperate traveler.",
  "Obsidian chips like glass, sharper than a surgeon's steel and dark as a moonless midnight sea.",
  "Step one: Brace the overhead timber. Step two: Swing with the hips. Step three: Pray for no collapse.",
  "Geodes look like ordinary rocks until you break their hearts open to reveal a city of purple amethyst.",
  "I found a vein of silver today that looked like frozen lightning trapped in a wall of grey granite.",
  "The deeper we go, the warmer the air gets. It feels less like a mine and more like a throat.",
  "Tungsten has the highest melting point of all metals, standing firm where others turn to liquid fire.",
  "They say the ghost of Old Miller still haunts the lower shafts, tapping out a code no one can break.",
  "A single spark in a dust-filled chamber is all it takes to turn a payday into a funeral pyre.",
  "Mohs scale measures hardness from one to ten; talc is a whisper, but diamond is a shout.",
  "The Great Gold Rush of 1849 transformed muddy camps into empires built on glitter and broken dreams.",
  "Magnetite pulls at the needle, a silent siren song guiding the lost toward the iron-rich depths.",
  "Mining isn't just digging; it's a conversation with the prehistoric, unearthing secrets long buried.",
  "Malachite swirls like a forest captured in stone, green ribbons of copper carbonated by time.",
  "The hoist cable frayed, humming a high-pitched note of impending disaster that echoed up the shaft.",
  "Rare earth elements are the silent engines of your technology, hidden in the dirt beneath your feet.",
  "Keep your lamp trimmed and your eyes sharp; the shadows in the crawlspace have a habit of moving.",
  "An alloy is a marriage of metals, where the strength of one covers the weakness of the other.",
  "The vein ran dry after forty feet. We found nothing but quartz and the bitter taste of failure.",
  "Cinnabar is a beautiful red poison, the heavy scent of mercury clinging to its crimson crystalline face.",
  "Every scar on a miner's hands is a map of the rock he has conquered and the debt he has paid.",
  "Fluorite glows under ultraviolet light, a secret neon party hidden inside a drab, cubic exterior.",
  "The foreman says we're 'extracting value,' but it feels more like we're skinning the world alive.",
  "Gold is chemically inert, meaning it will never rust, never tarnish, and never truly belong to you.",
  "I trade my daylight for stones. It's a fair swap until you forget what the sun looks like.",
  "Sulfur smells like the doorstep of hell, a yellow warning that some things are better left buried.",
  "Mica peels away in thin, transparent sheets like the pages of a book written by the earth itself.",
  "The drill bit shrieked against the basalt, a metallic scream that set my very teeth on edge.",
  "In the darkness, your ears become your eyes. Listen for the settling dust and the shifting shale.",
  "Emeralds are often found with 'jardin,' or tiny internal fractures that look like a mossy garden."
];