const miningQuotes = [
  "Stone chips flew as the pickaxe struck deep into the vein.",
  "The cavern walls glittered with hidden gems waiting to be found.",
  "He chipped away at the rock face until a glint of gold caught his eye.",
  "Deep beneath the mountain, the air was cool and thick with dust.",
  "Every strike of iron on stone sent sparks dancing in the dark.",
  "The tunnel narrowed as she pressed further into the ancient mine.",
  "Ore veins twisted through the granite like rivers frozen in time.",
  "His lantern flickered as the shaft descended into unknown depths.",
  "She had mined these hills for years and still the earth surprised her.",
  "The smell of iron and wet stone filled every breath underground.",
  "Rubies slept inside the rock, dreaming in shades of deep crimson.",
  "He tapped the wall gently, listening for the hollow sound of a pocket.",
  "The mountain gave up its secrets slowly and only to those who persisted.",
  "Quartz crystals jutted from the ceiling like frozen white flames.",
  "A good miner learns to read the rock the way others read a page.",
  "She struck the seam and a vein of copper blazed across the stone.",
  "Dust settled on his shoulders like grey snow in the lightless deep.",
  "The pickaxe rang against flint and the echo rolled down the passage.",
  "Each layer of stone was a page in a book written over millions of years.",
  "Underground, time moved differently, measured in depth rather than hours.",
];