const quotes = [
  "The woods are lovely, dark and deep, but I have promises to keep and miles to go before I sleep.",
  "Photosynthesis: converting light into life since the Devonian period. Respect the greenery.",
  "The gnarled branches reached out like skeletal fingers, clawing at the moonlight in a silent, wooden scream.",
  "Rooted deep, reaching high; a silent bridge between the earth and the sky.",
  "Dig a hole twice as wide as the root ball, backfill with native soil, and water deeply. Growth takes patience.",
  "The Elder Tree whispered secrets of the first age, its leaves shimmering with a light that predated the sun.",
  "The bio-luminescent flora of Kepler-186f pulsed in sync with the planet's magnetic heartbeat.",
  "Green leaves drink the sun / Roots hold tight to heavy earth / Quiet giants stand.",
  "If a tree falls in a silent forest and no one is around to hear it, does it still dream of the wind?",
  "Global reforestation initiatives reached an all-time high this quarter, with three million saplings planted in the tundra.",
  "Charming A-frame cabin nestled in ancient pines. Features include organic mulch views and squirrel-adjacent neighbors.",
  "Deep in the dark woods lived a witch whose house stood on massive, scaly chicken legs, hidden by the hemlocks.",
  "Bark, moss, leaf, and golden light filtering through the canopy like liquid honey.",
  "I'm totally stumped, said the oak to the lumberjack. It was a very short conversation.",
  "The rain slicked the needles of the evergreens like cheap pomade on a washed-up detective's hair.",
  "Our initials are still carved into the beech, a permanent scar of a love that didn't last as long as the timber.",
  "Survival tip: Moss doesn't always grow on the north side. Trust your compass, not the greenery.",
  "And the cedar shall reach the heavens, casting a shadow that covers the sins of the valley below.",
  "Honestly, just vibing under this willow right now. 10/10 would recommend for any existential crisis.",
  "Our corporate ESG goals include planting ten thousand saplings by Q4 to offset the carbon footprint of our cloud servers.",
  "Green lung, breathing slow, exhaling life into the gray smog of the city. A silent revolution of oxygen.",
  "The heavy footprints ended abruptly at the base of the hollow elm, leaving only the scent of damp earth and ozone.",
  "They say the forest moves when no one is watching, shifting its trails to trap the unwary in a labyrinth of thorns.",
  "Quercus robur, the English oak, supports over 2,300 species of wildlife. It is an entire city contained in a trunk.",
  "The forest remembers everything the wind forgets, storing the history of the world in its amber rings."
];