const quotes = [
  "The woods are lovely, dark and deep, but I have promises to keep and miles to go before I sleep.",
  "Photosynthesis: converting light into life since the Devonian period. Respect the greenery.",
  "The gnarled branches reached out like skeletal fingers, clawing at the moonlight in a silent, wooden scream.",
  "Rooted deep, reaching high; a silent bridge between the earth and the sky.",
  "Dig a hole twice as wide as the root ball, backfill with native soil, and water deeply. Growth takes patience.",
  "The Elder Tree whispered secrets of the first age, its leaves shimmering with a light that predated the sun.",
  "The bio-luminescent flora of Kepler-186f pulsed in sync with the planet's magnetic heartbeat.",
  "Green leaves drink the sun / Roots hold tight to heavy earth / Quiet giants stand.",
  "If a tree falls in a silent forest and no one is around to hear it, does it still dream of the wind?",
  "Global reforestation initiatives reached an all-time high this quarter, with three million saplings planted in the tundra.",
  "Charming A-frame cabin nestled in ancient pines. Features include organic mulch views and squirrel-adjacent neighbors.",
  "Deep in the dark woods lived a witch whose house stood on massive, scaly chicken legs, hidden by the hemlocks.",
  "Bark, moss, leaf, and golden light filtering through the canopy like liquid honey.",
  "I'm totally stumped, said the oak to the lumberjack. It was a very short conversation.",
  "The rain slicked the needles of the evergreens like cheap pomade on a washed-up detective's hair.",
  "Our initials are still carved into the beech, a permanent scar of a love that didn't last as long as the timber.",
  "Survival tip: Moss doesn't always grow on the north side. Trust your compass, not the greenery.",
  "And the cedar shall reach the heavens, casting a shadow that covers the sins of the valley below.",
  "Honestly, just vibing under this willow right now. 10/10 would recommend for any existential crisis.",
  "Our corporate ESG goals include planting ten thousand saplings by Q4 to offset the carbon footprint of our cloud servers.",
  "Green lung, breathing slow, exhaling life into the gray smog of the city. A silent revolution of oxygen.",
  "The heavy footprints ended abruptly at the base of the hollow elm, leaving only the scent of damp earth and ozone.",
  "They say the forest moves when no one is watching, shifting its trails to trap the unwary in a labyrinth of thorns.",
  "Quercus robur, the English oak, supports over 2,300 species of wildlife. It is an entire city contained in a trunk.",
  "The forest remembers everything the wind forgets, storing the history of the world in its amber rings.",
  "The oak stood defiant, a king in a crown of dying gold.",
  "Timber! The giant falls, and the earth trembles in its wake.",
  "Deep in the Charcoal Woods, the trees don't grow; they reach like charred skeletal fingers toward a sunless sky.",
  "I chopped so much wood today that my axe has a blister. Is that even possible? I need a vacation.",
  "The photosynthesis-to-biomass ratio in these Sector 4 bio-domes is exceeding all previous colonial projections.",
  "A sharp bit saves a sore back. Keep your grind consistent and your edge honed to a mirror finish.",
  "There is a particular silence that follows the felling of an ancient cedar—a heavy, judging quiet that lingers.",
  "Log Entry 42: The sap is glowing purple. I touched it, and now I can hear the ferns whispering about my boots.",
  "Knock on wood? I've been knocking all day with a five-pound felling axe, and I haven't seen a single spirit yet.",
  "The lumberjack's hands were like the bark itself: rough, scarred, and smelling of pine resin and old tobacco.",
  "If a tree falls in the forest and you're there to type it, does it make a sound or just a high-score notification?",
  "The xylem and phloem act as the tree's circulatory system, moving water and sugar through the vascular cambium.",
  "I saw a Dryad today. She told me to stop cutting her hair. I told her I was just giving her a very aggressive trim.",
  "Heartwood is the dead center of the tree, providing the structural integrity needed to withstand a hundred winter gales.",
  "One stroke for the hearth, one for the home, one for the winter that's coming too soon. Swing true, little woodman.",
  "The canopy was so thick it felt like walking through an emerald cathedral where the only hymns were sung by cicadas.",
  "Warning: Do not engage the hydraulic log-splitter without checking the pressure gauges. A burst line is a death sentence.",
  "The smell of fresh sawdust is the perfume of progress and the incense of the hardworking soul.",
  "In the dream, the stumps were teeth, and the forest was a mouth closing slowly around our tiny, wooden village.",
  "Bark is basically just tree armor. If I wore skin that thick, I'd probably be a lot better at taking criticism.",
  "The Ironwood of the Southern Isles is so dense it sinks in water, making it useless for boats but perfect for bludgeons.",
  "Yesterday a sapling, today a shade, tomorrow a timber, eventually a memory in the ashes of a cold fireplace.",
  "The wind howled through the pines like a choir of ghosts mourning the loss of their favorite climbing branches.",
  "The grip of the axe felt natural, like an extension of his own arm, a tool born of fire to conquer the wood.",
  "The redwoods are the skyscrapers of the natural world, reaching heights that make the clouds look like low-hanging fruit.",
  "Pulp. Press. Dry. The life of a tree is often destined to become the very paper you are ignoring right now.",
  "Heave! The rope went taut as the great pine finally surrendered to the inevitability of the gravity-fed earth.",
  "Is it woodcutting if I'm using a laser? My boss says 'yes,' but my soul says 'I am a space-faring heretic.'",
  "Copper leaves, silver rain, wooden heart, golden grain.",
  "The rings of the tree are a biography written in circles, detailing every drought and every bountiful spring of its life.",
  "Watch out for the 'widowmaker'—that dead branch hanging by a thread, just waiting for your first swing to let go.",
  "The forest doesn't care about your stories. It only cares about the sun, the rain, and the slow reach of its roots.",
  "I once knew a logger who could fell a spruce into a bucket from fifty yards away. He was a wizard with a wedge.",
  "Chlorophyll is the green pigment that allows plants to absorb energy from light. Without it, the world stays grey.",
  "The axe head was forged in the heat of a dying star, or so the blacksmith claimed. It cuts through oak like butter.",
  "Every splinter is a tiny lesson in physics and a painful reminder to wear your leather gloves at all times.",
  "The shadows in the Forbidden Grove move even when the wind is dead. I think I'll stick to the pines near the road.",
  "Softwood trees are gymnosperms. They don't have flowers, but they do have seeds. Also, they're great for building sheds.",
  "The sound of the saw is a rhythmic rasp, a metallic 'shush-shush' that lulls the forest into a deep, final sleep.",
  "I cut. I stack. I burn. I survive. This is the cycle of the woodsman, as old as the first spark of fire.",
  "The Banyan tree spreads its aerial roots like a thousand legs, walking slowly across the earth over centuries.",
  "Birch bark is the traveler's friend; it burns hot and fast, even when the world is weeping with autumn rain.",
  "My axe is dull, the wood is frozen, and my coffee is cold. This is the peak of the human experience, isn't it?",
  "The Druid's curse turned the logger's axe to glass the moment it touched the Sacred Rowan. A clear sign to leave.",
  "Dendrochronology: the study of tree rings to understand the past. Basically, trees are just really slow historians.",
  "The canopy shimmered with a million points of light as the morning sun broke through the morning mist.",
  "If you hit the wedge too hard, you risk splitting the handle. Finesse is just as important as brute strength in the woods.",
  "I'm not saying the tree started it, but it definitely stood in my way when I was trying to swing my axe.",
  "The scent of pine is the smell of winter's breath, trapped in needles and released by the bite of steel.",
  "A forest is a city where the buildings are made of leaves and the citizens are too busy growing to ever say hello.",
  "Hardwood is more difficult to cut but holds the heat of the fire far longer than the quick-burning poplar or fir.",
  "The ancient willow wept not for sadness, but because its branches were too heavy with the secrets of the valley.",
  "Logging in zero-G is a nightmare. You swing the axe and you end up spinning like a top while the tree just laughs.",
  "Chop your own wood, and it will warm you twice. Once while you work, and once when you finally light the match.",
  "The forest floor is a graveyard of giants, slowly turning back into the soil that will feed the next generation.",
  "A tree's height is limited by its ability to pull water against the force of gravity through its narrow capillaries.",
  "He carved her name into the bark, a small scar on a giant that would outlive them both by three hundred years.",
  "The saw blade screamed as it hit a hidden nail, a metallic shriek that echoed through the quiet logging camp.",
  "Wait. Did that stump just move? Or is the exhaustion finally making me hallucinate forest spirits again?",
  "The timber industry provides the backbone for civilization, from the floors we walk on to the roofs over our heads.",
  "Aspen groves are often one single organism, connected underground by a massive, ancient, and invisible root system.",
  "The sound of the axe on the frozen maple was like a gunshot in the still, biting air of the January morning.",
  "I'd tell you a joke about a tree, but it's a bit sappy.",
  "The great Sequoia stood for two thousand years, only to be turned into toothpicks by a man with a very loud machine.",
  "Safety first: always clear your escape path before you make the back cut. You don't want to be where the tree wants to be.",
  "The leaves turned from green to fire, a final, brilliant performance before they fell to the stage of the earth.",
  "The handle was made of hickory, chosen for its strength and its ability to take a beating without snapping in half.",
  "Is the forest shrinking, or are the shadows just getting longer? Either way, it's time to head back to the cabin.",
  "The cambium is the growing part of the trunk. It's the thin layer where all the magic—and the wood—actually happens.",
  "The old logger's beard was full of sawdust and wisdom, though he mostly used the latter to tell us to work harder.",
  "A forest fire is nature's way of hitting the reset button, clearing the old growth to make room for the new.",
  "The axe bit deep. The wood groaned. The world waited.",
  "The maple syrup season is a race against the rising sap and the warming sun, a sweet reward for a long, cold winter.",
  "In the end, we all return to the forest, either as the one who plants the tree or the one who rests beneath it."
];